name: Push Pages
on: [push]
jobs:
  push-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: true

      - name: Deploy ğŸš€
        if: github.ref != 'refs/heads/gh-pages'
        run: |
          git config --global user.email "spec-robot@apollographql.com"
          git config --global user.name "Spec Robot"
          git fetch origin gh-pages || true
          git checkout gh-pages || git checkout -b gh-pages

          # find the name of the branch or tag and bail if
          # we can't
          #
          # this is either terrible or beautiful or
          # perhaps both
          mkdir -p .scratch/${{ github.ref }}
          pushd .scratch/refs
<<<<<<< HEAD
          here=$(pwd)
          cd heads || cd tags
          # didn't go anywhere :(
          if [[ $(pwd) = $here ]]; then exit 1; fi
=======
          cd heads || cd tags
          # didn't go anywhere :(
          if [[ $(basename $(pwd)) = "refs" ]]; then exit 1; fi
          cd $(ls)
          pwd
>>>>>>> main
          version=$(basename $(pwd))          
          popd
          rm -rf .scratch

          # do a clean checkout
          rm -rf $version
          git clone . --branch $version --single-branch $version
          
          # retain git metadata but hide it from git
          mv $version/.git $version/_git
          
          # write a timestamp
          date > $version/__timestamp__

          # push it all
          git add .
          git commit -m "Updated $version"
          git push origin gh-pages
