name: Push Pages
on: [push]
jobs:
  push-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: true

      - name: Deploy ðŸš€
        run: |
          git checkout gh-pages || git checkout -b gh-pages
          date > now
          git add now
          git commit -m "Updated timestamp"
          git push
