name: Push Pages
on: [push]
jobs:
  push-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: true
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm install
      - run: npm run build
      - name: Find Version ğŸ•µğŸ½â€â™€ï¸
        id: find_version
        run: |
          # find the name of the branch or tag and bail if
          # we can't
          #
          # this is either terrible or beautiful or
          # perhaps both
          mkdir -p .scratch/${{ github.ref }}
          pushd .scratch/refs
          cd heads || cd tags
          # didn't go anywhere :(
          if [[ $(basename $(pwd)) = "refs" ]]; then exit 1; fi
          # dive in: find descends to the deepest directory,
          # whose name we grab with tail
          version=$(find * | tail -n 1)
          popd
          rm -rf .scratch
          echo "::set-output name=version::${version}"
      - name: Deploy ğŸš€
        if: github.ref != 'refs/heads/gh-pages'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.dist
          destination_dir: ${{ steps.find_version.outputs.version }}        
