name: Push Pages
on: [push]
jobs:
  push-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: true

      - name: Deploy ðŸš€
        run: |
          git config --global user.email "spec-robot@apollographql.com"
          git config --global user.name "Spec Robot"
          git checkout gh-pages || git checkout -b gh-pages
          date > __timestamp__
          
          branch=$(basename {{ github.ref }})
          date > $branch
#          git clone . --branch $(basename {{ github.ref }}) --single
          git add $branch
          git commit -m "Updated timestamp"
          git push origin gh-pages
